/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uiComponent;

import static driver.Driver.s;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import static uiComponent.LoginGUI.flag;

/**
 *
 * @author Armando
 */
public class StarterGUI extends javax.swing.JFrame {
    public static boolean progressFlag=false;

    /**
     * Creates new form StarterGUI
     */
    public StarterGUI() {
        initComponents();
        setProperties();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        status = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HL Manager");
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(51, 153, 0));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 390, -1));

        status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        status.setText("Initializing...");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        version.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        version.setText("v1.0");
        getContentPane().add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/hl logo trans 600x600.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/BG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    
    public  void iterate()
    {
            int num=0;
            while (num <= 1000) {
                
                jProgressBar1.setValue(num/10);
                if (num < 200)
                { 
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException e) { }
                    num += 1;                    
                }
                else 
                { 
                    //if access granted
                    if(flag)
                    {//System.out.println("flag is true");
                        try {
                            Thread.sleep(10);
                        } catch (InterruptedException e) { }
                        num += 1;                                     
                    }

                }

            }
            progressFlag=true;
            LoginGUI.pause();
    }
    
    public void promptPass(){
        this.pack();
        LoginGUI prompt = new LoginGUI();    
        prompt.setVisible(true);
    }
    
    private void setProperties() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("login-1-512 orange.png")));
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel status;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
